### ISSUE TITLE
add flag to allow scripted update

### ISSUE THREAD

**Issue by amenome** [pseudonomynous/animeDownloader#10]
Figure some way where we can call the script with a parameter that skips the input, and just does an update and quit.

```
docker run --interactive --tty -v /Volumes/6TB-SSD-RAID5.1/anime/:/home anime-py updateOnly
```

**Comment by pseudonomynous** [comment]
docker run --interactive --tty -v /Volumes/6TB-SSD-RAID5.1/anime/:/home anime-py update 

This command should work on the latest version. Might add same thing for "addAnime" in the future.
