### ISSUE TITLE
Fix script not finding all episodes

### ISSUE THREAD

**Issue by pseudonomynous** [pseudonomynous/animeDownloader#7]
Task: Currently, it assumes the default starting episode is 1, and find the final episode number by searching the page, and finding "0-x" on the page, which is the episode list. Unfortunately, sometimes seasons start on episode 0, or have decimal episodes like 24.5 and 24.9. Unfortunately, starting at episode 0 and incrementing by decimal won't work very easily because the page still loads, and there isn't technically a 404 error, just 404 printed on the page instead of the video player. Probably some way of parsing the page.

**Comment by amenome** [comment]
Example:

```
My Hero Academia, https://gogoanime.so/boku-no-hero-academia-2nd-season, 2, s
```

Barfs on ep0 and ep21

**Comment by pseudonomynous** [comment]
Solved this by parsing the home page for the anime for the actual episode links, rather than assuming the pattern for the first episode applied to all subsequent episodes. Should be far more robust.

**Comment by pseudonomynous** [comment]
Solved this by parsing the home page for the anime for the actual episode links, rather than assuming the pattern for the first episode applied to all subsequent episodes. Should be far more robust.
